package initialize

import (
	"gorm.io/gen"
)

func GenQuery() {
	// 创建查询对象,
	// 创建query,
	g := gen.NewGenerator(gen.Config{
		OutPath: "./query/",
		Mode:    gen.WithoutContext | gen.WithDefaultQuery | gen.WithQueryInterface, // generate mode
	})
	g.ApplyBasic(
	// 自动化模块表
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	)

	g.Execute()
	// query创建完毕
}
